version: '3'

services:
  wait:
    image: hello-world
    depends_on:
      mediawiki:
        condition: service_healthy
  mediawiki:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./dump.xml.gz:/app/dump.xml.gz
      - ./sb-wiki/settings/LocalSettings.php:/app/LocalSettings.php
  mariadb:
    image: mariadb:latest
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect"]
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: sponsor.ajay.app/donate
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
      MARIADB_MYSQL_LOCALHOST_USER: 'true'