version: '3.4'

services:
  wait:
    image: ghcr.io/mchangrh/elfbin:latest
    depends_on:
      mediawiki:
        condition: service_healthy
  mediawiki:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/w/Main_Page"]
      interval: 10s
      timeout: 30s
      retries: 10
    links:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./sponsorblock_wiki_current_revisions.xml.gz:/app/dump.xml.gz
      - ./sb-wiki/settings/LocalSettings.php:/app/LocalSettings.php
  mariadb:
    image: mariadb:latest
    restart: always
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect"]
      interval: 5s
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: sponsor.ajay.app/donate
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
      MARIADB_MYSQL_LOCALHOST_USER: 'true'