name: sb-wiki
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  DUMP_NAME: dump.xml.gz
  FILENAME: sponsorblock_wiki_current_revisions.xml.gz

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache/restore@v3
        with:
          path: ${FILENAME}
          key: current_revisions
      - name: Download db dump
        run: wget https://wiki.sponsor.ajay.app/images/${FILENAME} -N --no-if-modified-since
      - uses: actions/cache/save@v3
        with:
          path: ${FILENAME}
          key: current_revisions
      - run: docker compose up --build -d
      - name: Checkout downloader
        uses: actions/checkout@v3
        with:
         repository: SolidCharity/exportMediaWiki2HTML
         path: export-html
      - uses: actions/setup-python@v4
      - name: run downloader
        run: cd export-html && pip install -r requirements.txt && python exportMediaWiki2Html.py --url http://localhost:8080 --no-ssl --shortUrl w/
      - name: move Main_Page to index
        run: cd export-html/export && cp Main_Page.html index.html
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'export-html/export'
      - uses: actions/deploy-pages@v2