name: sb-wiki
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 2 * *'

env:
  DUMP_NAME: dump.xml.gz
  FILENAME: sponsorblock_wiki_current_revisions.xml.gz

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download db dump
        run: wget https://wiki.sponsor.ajay.app/images/${FILENAME} -O ${FILENAME}
      - name: bump local date
        run: date > last-update
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Automated last-update bump
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      - run: docker compose up --build -d
      - name: Checkout downloader
        uses: actions/checkout@v4
        with:
         repository: SolidCharity/exportMediaWiki2HTML
         path: export-html
      - uses: actions/setup-python@v5
      - name: run downloader
        run: cd export-html && pip install -r requirements.txt && python exportMediaWiki2Html.py --url http://localhost:8080 --no-ssl --shortUrl w/
      - name: move Main_Page to index
        run: cd export-html/export && cp Main_Page.html index.html
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'export-html/export'
      - uses: actions/deploy-pages@v4