name: request-dump
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Request database dump
        run: curl -X POST https://wiki.sponsor.ajay.app/w/Special:RequestDump